######################################################################
# Automatically generated by qmake (2.01a) mié oct 8 20:48:13 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += ventana.cpp
