######################################################################
# Automatically generated by qmake (2.01a) s�b oct 25 10:48:44 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += concepto.h \
    mapa.h
SOURCES += concepto.cpp main.cpp  \
    mapa.cpp
