######################################################################
# Automatically generated by qmake (2.01a) sáb oct 25 10:48:44 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += concepto.h pareja.h
SOURCES += concepto.cpp main.cpp pareja.cpp
